import type { CSSProperties } from "react";

/** Co-located styles for the shared Context tab panel (`ContextDocsPanel` + `DocRow` + `SerializesAsBox`). */
export const s = {
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 8, flexWrap: "wrap" } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  filter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
  } satisfies CSSProperties,
  filterIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 12 } satisfies CSSProperties,
  tokens: (tier: "ok" | "amber" | "red"): CSSProperties => ({
    fontSize: 12,
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    color: tier === "red" ? "var(--danger)" : tier === "amber" ? "var(--warn)" : "var(--text-muted)",
    fontWeight: tier === "ok" ? 400 : 700,
    marginBottom: 12,
  }),
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (attached: boolean, dragging: boolean, missing: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 8,
    border: `1px solid ${attached ? "var(--border-strong)" : "var(--border)"}`,
    background: attached ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: dragging ? 0.6 : missing ? 0.7 : 1,
  }),
  handle: (draggable: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    padding: 2,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: draggable ? "grab" : "not-allowed",
    opacity: draggable ? 1 : 0.4,
    touchAction: "none",
  }),
  path: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  missingNote: { fontSize: 11, color: "var(--warn)" } satisfies CSSProperties,
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "4px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-muted)",
    fontSize: 12,
    cursor: "pointer",
  } satisfies CSSProperties,
  serializesBox: {
    marginTop: 16,
    padding: 14,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  serializesHeading: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginBottom: 4,
  } satisfies CSSProperties,
  serializesHint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 10 } satisfies CSSProperties,
  serializesPath: {
    fontSize: 12,
    color: "var(--text-secondary)",
    padding: "3px 0",
  } satisfies CSSProperties,
} as const;
