import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page (N6). */
export const s = {
  page: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  listPane: {
    width: 340,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "14px 16px 10px",
    flexShrink: 0,
  } satisfies CSSProperties,
  title: { fontSize: 16, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  list: { flex: 1, overflow: "auto", padding: "0 10px 10px", display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  row: (selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 7,
    cursor: "pointer",
    background: selected ? "var(--bg-hover)" : "transparent",
    border: `1px solid ${selected ? "var(--border-strong)" : "transparent"}`,
  }),
  rowPath: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  usedBy: {
    flexShrink: 0,
    fontSize: 11,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  footer: {
    padding: "10px 16px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  truncatedBanner: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px",
    fontSize: 12,
    color: "var(--warning, #b45309)",
    flexShrink: 0,
  } satisfies CSSProperties,
  previewPane: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  previewHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "16px 24px 12px",
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
  } satisfies CSSProperties,
  previewBody: { flex: 1, overflow: "auto", padding: 24 } satisfies CSSProperties,
  placeholder: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies CSSProperties,
} as const;
